export interface ReconcileInput {
  runId: string;
  iid: number;
  branch: string;
  baseBranch: string;
  workspacePath: string;
  attempt: number;
  agentSummary?: string | undefined;
  agentValidation?: string | undefined;
  agentRisks?: string | undefined;
  noCodeChangeReason?: string | undefined;
  issueUrl: string;
  issueIdentifier: string;
  runningLabel: string;
  handoffLabel: string;
  git: GitSlice;
  gitlab: GitLabReconcileSlice;
  onEvent: (event: ReconcileEvent) => void;
}

export interface ReconcileEvent {
  type: string;
  runId: string;
  ts: string;
  detail: Record<string, unknown>;
}

interface GitSlice {
  hasNewCommits(cwd: string, baseBranch: string): Promise<boolean>;
  push(cwd: string, branch: string): Promise<void>;
}

interface GitLabReconcileSlice {
  findMergeRequest(sourceBranch: string): Promise<{ iid: number; title: string; description: string } | null>;
  createMergeRequest(opts: {
    sourceBranch: string;
    targetBranch: string;
    title: string;
    description: string;
  }): Promise<{ iid: number }>;
  updateMergeRequest(mrIid: number, opts: { title?: string; description?: string }): Promise<void>;
  findWorkpadNote(issueIid: number, marker: string): Promise<{ id: number; body: string } | null>;
  createNote(issueIid: number, body: string): Promise<{ id: number }>;
  updateNote(issueIid: number, noteId: number, body: string): Promise<void>;
  transitionLabels(
    iid: number,
    opts: { add: string[]; remove: string[] },
  ): Promise<void>;
}

function buildMrBody(input: ReconcileInput): string {
  const summary =
    input.agentSummary ||
    "Codex completed without a structured summary; see commits.";
  const validation = input.agentValidation || "(no validation summary)";
  const risks = input.agentRisks || "(none reported)";

  return [
    `Issue: ${input.issueUrl}`,
    "",
    "## Implementation summary",
    summary,
    "",
    "## Validation",
    validation,
    "",
    "## Risks",
    risks,
    "",
    "---",
    `Generated by IssuePilot for ${input.issueIdentifier}, attempt ${input.attempt}.`,
  ].join("\n");
}

function buildWorkpadNote(input: ReconcileInput): string {
  const marker = `<!-- issuepilot:run:${input.runId} -->`;
  return [
    marker,
    `**IssuePilot run** \`${input.runId}\` — attempt ${input.attempt}`,
    "",
    `- Branch: \`${input.branch}\``,
    `- Status: completed`,
    `- Summary: ${input.agentSummary || "(no summary)"}`,
    `- Validation: ${input.agentValidation || "(none)"}`,
    `- Risks: ${input.agentRisks || "(none)"}`,
    ...(input.noCodeChangeReason
      ? [`- No code changes: ${input.noCodeChangeReason}`]
      : []),
  ].join("\n");
}

function now(): string {
  return new Date().toISOString();
}

export async function reconcile(input: ReconcileInput): Promise<void> {
  const hasCommits = await input.git.hasNewCommits(
    input.workspacePath,
    input.baseBranch,
  );

  if (!hasCommits) {
    const noCodeChangeReason = input.noCodeChangeReason?.trim();
    input.onEvent({
      type: "reconcile_no_commits",
      runId: input.runId,
      ts: now(),
      detail: { branch: input.branch },
    });

    if (!noCodeChangeReason) {
      throw new Error(
        `Reconcile found no new commits on branch ${input.branch} and no explicit no-code-change reason.`,
      );
    }

    const marker = `<!-- issuepilot:run:${input.runId} -->`;
    const existingNote = await input.gitlab.findWorkpadNote(
      input.iid,
      marker,
    );
    const noteBody = buildWorkpadNote({
      ...input,
      noCodeChangeReason,
    });

    if (!existingNote) {
      const note = await input.gitlab.createNote(input.iid, noteBody);
      input.onEvent({
        type: "gitlab_workpad_note_created",
        runId: input.runId,
        ts: now(),
        detail: { noteId: note.id, branch: input.branch },
      });
    } else {
      await input.gitlab.updateNote(input.iid, existingNote.id, noteBody);
      input.onEvent({
        type: "gitlab_workpad_note_updated",
        runId: input.runId,
        ts: now(),
        detail: { noteId: existingNote.id, branch: input.branch },
      });
    }

    await transitionToHandoff(input);
    return;
  }

  await input.git.push(input.workspacePath, input.branch);
  input.onEvent({
    type: "gitlab_push",
    runId: input.runId,
    ts: now(),
    detail: { branch: input.branch },
  });

  const existingMr = await input.gitlab.findMergeRequest(input.branch);
  const mrBody = buildMrBody(input);

  if (!existingMr) {
    const mr = await input.gitlab.createMergeRequest({
      sourceBranch: input.branch,
      targetBranch: input.baseBranch,
      title: `[IssuePilot] ${input.issueIdentifier}`,
      description: mrBody,
    });
    input.onEvent({
      type: "gitlab_mr_created",
      runId: input.runId,
      ts: now(),
      detail: { mrIid: mr.iid, branch: input.branch },
    });
  } else {
    await input.gitlab.updateMergeRequest(existingMr.iid, {
      description: mrBody,
    });
    input.onEvent({
      type: "gitlab_mr_updated",
      runId: input.runId,
      ts: now(),
      detail: { mrIid: existingMr.iid },
    });
  }

  const marker = `<!-- issuepilot:run:${input.runId} -->`;
  const existingNote = await input.gitlab.findWorkpadNote(
    input.iid,
    marker,
  );
  const noteBody = buildWorkpadNote(input);

  if (!existingNote) {
    await input.gitlab.createNote(input.iid, noteBody);
  } else {
    await input.gitlab.updateNote(input.iid, existingNote.id, noteBody);
  }

  await transitionToHandoff(input);
}

async function transitionToHandoff(input: ReconcileInput): Promise<void> {
  await input.gitlab.transitionLabels(input.iid, {
    add: [input.handoffLabel],
    remove: [input.runningLabel],
  });
  input.onEvent({
    type: "gitlab_labels_transitioned",
    runId: input.runId,
    ts: now(),
    detail: { add: [input.handoffLabel], remove: [input.runningLabel] },
  });
}
