import type { RunReportArtifact } from "@issuepilot/shared-contracts";

import { renderHandoffNote } from "../reports/render.js";

export interface ReconcileInput {
  runId: string;
  iid: number;
  branch: string;
  baseBranch: string;
  workspacePath: string;
  attempt: number;
  agentSummary?: string | undefined;
  agentValidation?: string | undefined;
  agentRisks?: string | undefined;
  noCodeChangeReason?: string | undefined;
  issueUrl: string;
  issueIdentifier: string;
  runningLabel: string;
  handoffLabel: string;
  reworkLabel: string;
  git: GitSlice;
  gitlab: GitLabReconcileSlice;
  onEvent: (event: ReconcileEvent) => void;
  /**
   * V2.5 Command Center: when present, the handoff workpad note is rendered
   * from the run report artifact instead of the legacy `buildHandoffNote`
   * fallback. Daemon-driven reconcile passes the latest report so a single
   * fact source covers dashboard, notes and exports.
   */
  report?: RunReportArtifact | undefined;
}

/**
 * Side-effects metadata returned to the daemon so it can update the run
 * report with the handoff note id and the MR coordinates.
 */
export interface ReconcileResult {
  mergeRequest?: { iid: number; webUrl?: string };
  handoffNoteId?: number;
  hadNewCommits: boolean;
}

export interface ReconcileEvent {
  type: string;
  runId: string;
  ts: string;
  detail: Record<string, unknown>;
}

interface GitSlice {
  hasNewCommits(cwd: string, baseBranch: string): Promise<boolean>;
  push(cwd: string, branch: string): Promise<void>;
}

interface GitLabReconcileSlice {
  findMergeRequest(sourceBranch: string): Promise<{
    iid: number;
    title: string;
    description: string;
    webUrl?: string;
  } | null>;
  createMergeRequest(opts: {
    sourceBranch: string;
    targetBranch: string;
    title: string;
    description: string;
  }): Promise<{ iid: number; webUrl?: string }>;
  updateMergeRequest(
    mrIid: number,
    opts: { title?: string; description?: string },
  ): Promise<void>;
  findWorkpadNote(
    issueIid: number,
    marker: string,
  ): Promise<{ id: number; body: string } | null>;
  createNote(issueIid: number, body: string): Promise<{ id: number }>;
  updateNote(issueIid: number, noteId: number, body: string): Promise<void>;
  transitionLabels(
    iid: number,
    opts: { add: string[]; remove: string[] },
  ): Promise<void>;
}

function buildMrBody(input: ReconcileInput): string {
  const summary =
    input.agentSummary ||
    "Codex completed without a structured summary; see commits.";
  const validation = input.agentValidation || "(no validation summary)";
  const risks = input.agentRisks || "(none reported)";

  return [
    `Issue: ${input.issueUrl}`,
    "",
    "## Implementation summary",
    summary,
    "",
    "## Validation",
    validation,
    "",
    "## Risks",
    risks,
    "",
    "---",
    `Generated by IssuePilot for ${input.issueIdentifier}, attempt ${input.attempt}.`,
  ].join("\n");
}

function fallbackText(value: string | undefined, fallback: string): string {
  const trimmed = value?.trim();
  return trimmed ? trimmed : fallback;
}

function mrLine(mr: { iid: number; webUrl?: string } | null): string {
  if (!mr) return "not created";
  return mr.webUrl ? `!${mr.iid} ${mr.webUrl}` : `!${mr.iid}`;
}

function buildHandoffNote(
  input: ReconcileInput,
  mr: { iid: number; webUrl?: string } | null,
): string {
  const summary = fallbackText(
    input.agentSummary,
    input.noCodeChangeReason
      ? `No code changes: ${input.noCodeChangeReason}`
      : "Codex completed without a structured summary; see commits.",
  );
  const validation = fallbackText(
    input.agentValidation,
    input.noCodeChangeReason
      ? "No validation command was reported for this no-code-change run."
      : "(no validation summary)",
  );
  const risks = fallbackText(input.agentRisks, "None reported.");

  return [
    `<!-- issuepilot:run:${input.runId} -->`,
    "## IssuePilot handoff",
    "",
    `- Status: ${input.handoffLabel}`,
    `- Run: \`${input.runId}\``,
    `- Attempt: ${input.attempt}`,
    `- Branch: \`${input.branch}\``,
    `- MR: ${mrLine(mr)}`,
    "",
    "### What changed",
    summary,
    "",
    "### Validation",
    validation,
    "",
    "### Risks / follow-ups",
    risks,
    "",
    "### Next action",
    `Review and merge the MR, or move this Issue to \`${input.reworkLabel}\` if changes are required.`,
  ].join("\n");
}

function now(): string {
  return new Date().toISOString();
}

function renderNoteBody(
  input: ReconcileInput,
  mr: { iid: number; webUrl?: string } | null,
): string {
  if (input.report) {
    const reportForNote: RunReportArtifact = mr
      ? {
          ...input.report,
          mergeRequest: {
            iid: mr.iid,
            url: mr.webUrl ?? "",
            state: "opened",
          },
        }
      : input.report;
    return renderHandoffNote(reportForNote, {
      handoffLabel: input.handoffLabel,
    });
  }
  return buildHandoffNote(input, mr);
}

export async function reconcile(input: ReconcileInput): Promise<ReconcileResult> {
  const hasCommits = await input.git.hasNewCommits(
    input.workspacePath,
    input.baseBranch,
  );

  if (!hasCommits) {
    const noCodeChangeReason = input.noCodeChangeReason?.trim();
    input.onEvent({
      type: "reconcile_no_commits",
      runId: input.runId,
      ts: now(),
      detail: { branch: input.branch },
    });

    if (!noCodeChangeReason) {
      throw new Error(
        `Reconcile found no new commits on branch ${input.branch} and no explicit no-code-change reason.`,
      );
    }

    const marker = `<!-- issuepilot:run:${input.runId} -->`;
    const existingNote = await input.gitlab.findWorkpadNote(input.iid, marker);
    const noteBody = renderNoteBody({ ...input, noCodeChangeReason }, null);

    let handoffNoteId: number | undefined;
    if (!existingNote) {
      const note = await input.gitlab.createNote(input.iid, noteBody);
      handoffNoteId = note.id;
      input.onEvent({
        type: "gitlab_workpad_note_created",
        runId: input.runId,
        ts: now(),
        detail: { noteId: note.id, branch: input.branch },
      });
    } else {
      await input.gitlab.updateNote(input.iid, existingNote.id, noteBody);
      handoffNoteId = existingNote.id;
      input.onEvent({
        type: "gitlab_workpad_note_updated",
        runId: input.runId,
        ts: now(),
        detail: { noteId: existingNote.id, branch: input.branch },
      });
    }

    await transitionToHandoff(input);
    return {
      hadNewCommits: false,
      ...(handoffNoteId !== undefined ? { handoffNoteId } : {}),
    };
  }

  await input.git.push(input.workspacePath, input.branch);
  input.onEvent({
    type: "gitlab_push",
    runId: input.runId,
    ts: now(),
    detail: { branch: input.branch },
  });

  const existingMr = await input.gitlab.findMergeRequest(input.branch);
  const mrBody = buildMrBody(input);

  let handoffMr: { iid: number; webUrl?: string };
  if (!existingMr) {
    const mr = await input.gitlab.createMergeRequest({
      sourceBranch: input.branch,
      targetBranch: input.baseBranch,
      title: `[IssuePilot] ${input.issueIdentifier}`,
      description: mrBody,
    });
    handoffMr = mr;
    input.onEvent({
      type: "gitlab_mr_created",
      runId: input.runId,
      ts: now(),
      detail: { mrIid: mr.iid, branch: input.branch },
    });
  } else {
    await input.gitlab.updateMergeRequest(existingMr.iid, {
      description: mrBody,
    });
    handoffMr = existingMr;
    input.onEvent({
      type: "gitlab_mr_updated",
      runId: input.runId,
      ts: now(),
      detail: { mrIid: existingMr.iid },
    });
  }

  const marker = `<!-- issuepilot:run:${input.runId} -->`;
  const existingNote = await input.gitlab.findWorkpadNote(input.iid, marker);
  const noteBody = renderNoteBody(input, handoffMr);

  let handoffNoteId: number | undefined;
  if (!existingNote) {
    const note = await input.gitlab.createNote(input.iid, noteBody);
    handoffNoteId = note.id;
  } else {
    await input.gitlab.updateNote(input.iid, existingNote.id, noteBody);
    handoffNoteId = existingNote.id;
  }

  await transitionToHandoff(input);
  return {
    hadNewCommits: true,
    mergeRequest: handoffMr,
    ...(handoffNoteId !== undefined ? { handoffNoteId } : {}),
  };
}

async function transitionToHandoff(input: ReconcileInput): Promise<void> {
  await input.gitlab.transitionLabels(input.iid, {
    add: [input.handoffLabel],
    remove: [input.runningLabel],
  });
  input.onEvent({
    type: "gitlab_labels_transitioned",
    runId: input.runId,
    ts: now(),
    detail: { add: [input.handoffLabel], remove: [input.runningLabel] },
  });
}
